// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/ar/edu/unnoba/compilador/lexico.flex

package ar.edu.unnoba.compilador;

import java.util.ArrayList;
import java.util.List;

import java_cup.runtime.*;
import java_cup.sym;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class MiLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\7\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u1f00\1\u2400\1\u2500\2\u1f00\31\u0100\1\u2600\121\u0100\1\u2700"+
    "\4\u0100\1\u2800\1\u0100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00"+
    "\1\u2e00\53\u0100\1\u2f00\41\u1f00\1\u0100\1\u3000\1\u3100\1\u0100"+
    "\1\u3200\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u3a00\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u4100\1\u1f00\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00"+
    "\1\u4f00\1\u5000\1\u1f00\3\u0100\1\u5100\1\u5200\1\u5300\12\u1f00"+
    "\4\u0100\1\u5400\17\u1f00\2\u0100\1\u5500\41\u1f00\2\u0100\1\u5600"+
    "\1\u5700\2\u1f00\1\u5800\1\u5900\27\u0100\1\u5a00\2\u0100\1\u5b00"+
    "\45\u1f00\1\u0100\1\u5c00\1\u5d00\11\u1f00\1\u5e00\24\u1f00\1\u5f00"+
    "\1\u6000\1\u1f00\1\u6100\1\u6200\1\u6300\1\u6400\2\u1f00\1\u6500"+
    "\5\u1f00\1\u6600\1\u6700\1\u6800\5\u1f00\1\u6900\1\u6a00\4\u1f00"+
    "\1\u6b00\2\u1f00\1\u6c00\16\u1f00\246\u0100\1\u6d00\20\u0100\1\u6e00"+
    "\1\u6f00\25\u0100\1\u7000\34\u0100\1\u7100\14\u1f00\2\u0100\1\u7200"+
    "\u0b06\u1f00\1\u7300\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\5\1\22\0\1\1\7\0\1\2\1\3\1\4"+
    "\1\5\1\0\1\6\1\0\1\7\1\10\11\11\7\0"+
    "\32\12\4\0\1\12\1\0\1\13\1\14\2\12\1\15"+
    "\1\16\1\17\1\12\1\20\2\12\1\21\1\12\1\22"+
    "\1\23\2\12\1\24\1\12\1\25\6\12\12\0\1\1"+
    "\32\0\1\1\11\0\1\12\12\0\1\12\4\0\1\12"+
    "\5\0\27\12\1\0\37\12\1\0\u01ca\12\4\0\14\12"+
    "\16\0\5\12\7\0\1\12\1\0\1\12\21\0\160\26"+
    "\5\12\1\0\2\12\2\0\4\12\1\0\1\12\6\0"+
    "\1\12\1\0\3\12\1\0\1\12\1\0\24\12\1\0"+
    "\123\12\1\0\213\12\1\0\7\26\246\12\1\0\46\12"+
    "\2\0\1\12\6\0\51\12\10\0\55\26\1\0\1\26"+
    "\1\0\2\26\1\0\2\26\1\0\1\26\10\0\33\12"+
    "\4\0\4\12\35\0\13\26\5\0\53\12\37\26\4\0"+
    "\2\12\1\26\143\12\1\0\1\12\7\26\2\0\6\26"+
    "\2\12\2\26\1\0\4\26\2\12\12\26\3\12\2\0"+
    "\1\12\20\0\1\12\1\26\36\12\33\26\2\0\131\12"+
    "\13\26\1\12\16\0\12\26\41\12\11\26\2\12\4\0"+
    "\1\12\2\0\1\26\2\0\26\12\4\26\1\12\11\26"+
    "\1\12\3\26\1\12\5\26\22\0\31\12\3\26\4\0"+
    "\13\12\65\0\25\12\1\0\10\12\25\0\17\26\1\0"+
    "\41\26\66\12\3\26\1\12\22\26\1\12\7\26\12\12"+
    "\2\26\2\0\12\26\1\0\20\12\3\26\1\0\10\12"+
    "\2\0\2\12\2\0\26\12\1\0\7\12\1\0\1\12"+
    "\3\0\4\12\2\0\1\26\1\12\7\26\2\0\2\26"+
    "\2\0\3\26\1\12\10\0\1\26\4\0\2\12\1\0"+
    "\3\12\2\26\2\0\12\26\2\12\12\0\1\12\1\0"+
    "\1\26\2\0\3\26\1\0\6\12\4\0\2\12\2\0"+
    "\26\12\1\0\7\12\1\0\2\12\1\0\2\12\1\0"+
    "\2\12\2\0\1\26\1\0\5\26\4\0\2\26\2\0"+
    "\3\26\3\0\1\26\7\0\4\12\1\0\1\12\7\0"+
    "\14\26\3\12\1\26\13\0\3\26\1\0\11\12\1\0"+
    "\3\12\1\0\26\12\1\0\7\12\1\0\2\12\1\0"+
    "\5\12\2\0\1\26\1\12\10\26\1\0\3\26\1\0"+
    "\3\26\2\0\1\12\17\0\2\12\2\26\2\0\12\26"+
    "\11\0\1\12\6\26\1\0\3\26\1\0\10\12\2\0"+
    "\2\12\2\0\26\12\1\0\7\12\1\0\2\12\1\0"+
    "\5\12\2\0\1\26\1\12\7\26\2\0\2\26\2\0"+
    "\3\26\10\0\2\26\4\0\2\12\1\0\3\12\2\26"+
    "\2\0\12\26\1\0\1\12\20\0\1\26\1\12\1\0"+
    "\6\12\3\0\3\12\1\0\4\12\3\0\2\12\1\0"+
    "\1\12\1\0\2\12\3\0\2\12\3\0\3\12\3\0"+
    "\14\12\4\0\5\26\3\0\3\26\1\0\4\26\2\0"+
    "\1\12\6\0\1\26\16\0\12\26\20\0\5\26\10\12"+
    "\1\0\3\12\1\0\27\12\1\0\20\12\3\0\1\12"+
    "\7\26\1\0\3\26\1\0\4\26\7\0\2\26\1\0"+
    "\3\12\5\0\2\12\2\26\2\0\12\26\20\0\1\12"+
    "\3\26\1\0\10\12\1\0\3\12\1\0\27\12\1\0"+
    "\12\12\1\0\5\12\2\0\1\26\1\12\7\26\1\0"+
    "\3\26\1\0\4\26\7\0\2\26\7\0\1\12\1\0"+
    "\2\12\2\26\2\0\12\26\1\0\2\12\15\0\4\26"+
    "\1\0\10\12\1\0\3\12\1\0\51\12\2\26\1\12"+
    "\7\26\1\0\3\26\1\0\4\26\1\12\5\0\3\12"+
    "\1\26\7\0\3\12\2\26\2\0\12\26\12\0\6\12"+
    "\2\0\2\26\1\0\22\12\3\0\30\12\1\0\11\12"+
    "\1\0\1\12\2\0\7\12\3\0\1\26\4\0\6\26"+
    "\1\0\1\26\1\0\10\26\6\0\12\26\2\0\2\26"+
    "\15\0\60\12\1\26\2\12\7\26\5\0\7\12\10\26"+
    "\1\0\12\26\47\0\2\12\1\0\1\12\1\0\5\12"+
    "\1\0\30\12\1\0\1\12\1\0\12\12\1\26\2\12"+
    "\11\26\1\12\2\0\5\12\1\0\1\12\1\0\6\26"+
    "\2\0\12\26\2\0\4\12\40\0\1\12\27\0\2\26"+
    "\6\0\12\26\13\0\1\26\1\0\1\26\1\0\1\26"+
    "\4\0\2\26\10\12\1\0\44\12\4\0\24\26\1\0"+
    "\2\26\5\12\13\26\1\0\44\26\11\0\1\26\71\0"+
    "\53\12\24\26\1\12\12\26\6\0\6\12\4\26\4\12"+
    "\3\26\1\12\3\26\2\12\7\26\3\12\4\26\15\12"+
    "\14\26\1\12\17\26\2\0\46\12\1\0\1\12\5\0"+
    "\1\12\2\0\53\12\1\0\115\12\1\0\4\12\2\0"+
    "\7\12\1\0\1\12\1\0\4\12\2\0\51\12\1\0"+
    "\4\12\2\0\41\12\1\0\4\12\2\0\7\12\1\0"+
    "\1\12\1\0\4\12\2\0\17\12\1\0\71\12\1\0"+
    "\4\12\2\0\103\12\2\0\3\26\40\0\20\12\20\0"+
    "\126\12\2\0\6\12\3\0\u016c\12\2\0\21\12\1\1"+
    "\32\12\5\0\113\12\3\0\3\26\10\12\7\0\15\12"+
    "\1\0\4\12\3\26\13\0\22\12\3\26\13\0\22\12"+
    "\2\26\14\0\15\12\1\0\3\12\1\0\2\26\14\0"+
    "\64\12\40\26\3\0\1\12\4\0\1\12\1\26\2\0"+
    "\12\26\41\0\3\26\2\0\12\26\6\0\131\12\7\0"+
    "\5\12\2\26\42\12\1\26\1\12\5\0\106\12\12\0"+
    "\37\12\1\0\14\26\4\0\14\26\12\0\12\26\36\12"+
    "\2\0\5\12\13\0\54\12\4\0\32\12\6\0\12\26"+
    "\46\0\27\12\5\26\4\0\65\12\12\26\1\0\35\26"+
    "\2\0\13\26\6\0\12\26\15\0\1\12\10\0\17\26"+
    "\101\0\5\26\57\12\21\26\7\12\4\0\12\26\21\0"+
    "\11\26\14\0\3\26\36\12\15\26\2\12\12\26\54\12"+
    "\16\26\14\0\44\12\24\26\10\0\12\26\3\0\3\12"+
    "\12\26\44\12\2\0\11\12\7\0\53\12\2\0\3\12"+
    "\20\0\3\26\1\0\25\26\4\12\1\26\6\12\1\26"+
    "\2\12\3\26\1\12\5\0\300\12\72\26\1\0\5\26"+
    "\26\12\2\0\6\12\2\0\46\12\2\0\6\12\2\0"+
    "\10\12\1\0\1\12\1\0\1\12\1\0\1\12\1\0"+
    "\37\12\2\0\65\12\1\0\7\12\1\0\1\12\3\0"+
    "\3\12\1\0\7\12\3\0\4\12\2\0\6\12\4\0"+
    "\15\12\5\0\3\12\1\0\7\12\3\0\13\1\35\0"+
    "\2\1\5\0\1\1\17\0\2\26\23\0\1\26\12\0"+
    "\1\1\21\0\1\12\15\0\1\12\20\0\15\12\63\0"+
    "\41\26\21\0\1\12\4\0\1\12\2\0\12\12\1\0"+
    "\1\12\3\0\5\12\6\0\1\12\1\0\1\12\1\0"+
    "\1\12\1\0\4\12\1\0\13\12\2\0\4\12\5\0"+
    "\5\12\4\0\1\12\21\0\43\26\2\12\4\26\u022d\0"+
    "\64\26\26\0\57\12\1\0\57\12\1\0\205\12\6\0"+
    "\4\12\3\26\2\12\14\0\46\12\1\0\1\12\5\0"+
    "\1\12\2\0\70\12\7\0\1\12\17\0\1\26\27\12"+
    "\11\0\7\12\1\0\7\12\1\0\7\12\1\0\7\12"+
    "\1\0\7\12\1\0\7\12\1\0\7\12\1\0\7\12"+
    "\1\0\40\26\57\0\1\12\320\0\1\1\4\0\2\12"+
    "\1\26\31\0\17\26\1\0\5\12\2\0\3\26\2\12"+
    "\4\0\126\12\2\0\2\26\2\0\3\12\1\0\132\12"+
    "\1\0\4\12\5\0\53\12\1\0\136\12\21\0\33\12"+
    "\65\0\306\12\112\0\360\12\20\0\215\12\103\0\56\12"+
    "\2\0\15\12\3\0\20\12\12\26\2\12\24\0\57\12"+
    "\4\26\1\0\12\26\1\0\37\12\2\26\106\12\14\26"+
    "\45\0\11\12\2\0\147\12\2\0\65\12\2\0\5\12"+
    "\60\0\13\12\1\26\3\12\1\26\4\12\1\26\27\12"+
    "\5\26\30\0\64\12\14\0\2\26\62\12\22\26\12\0"+
    "\12\26\6\0\22\26\6\12\3\0\1\12\1\0\2\12"+
    "\13\26\34\12\10\26\2\0\27\12\15\26\14\0\35\12"+
    "\3\0\4\26\57\12\16\26\16\0\1\12\12\26\6\0"+
    "\5\12\1\26\12\12\12\26\5\12\1\0\51\12\16\26"+
    "\11\0\3\12\1\26\10\12\2\26\2\0\12\26\6\0"+
    "\27\12\3\0\1\12\3\26\62\12\1\26\1\12\3\26"+
    "\2\12\2\26\5\12\2\26\1\12\1\26\1\12\30\0"+
    "\3\12\2\0\13\12\5\26\2\0\3\12\2\26\12\0"+
    "\6\12\2\0\6\12\2\0\6\12\11\0\7\12\1\0"+
    "\7\12\1\0\53\12\1\0\14\12\10\0\163\12\10\26"+
    "\1\0\2\26\2\0\12\26\6\0\244\12\14\0\27\12"+
    "\4\0\61\12\4\0\156\12\2\0\152\12\46\0\7\12"+
    "\14\0\5\12\5\0\1\12\1\26\12\12\1\0\15\12"+
    "\1\0\5\12\1\0\1\12\1\0\2\12\1\0\2\12"+
    "\1\0\154\12\41\0\153\12\22\0\100\12\2\0\66\12"+
    "\50\0\14\12\4\0\20\26\20\0\20\26\3\0\2\26"+
    "\30\0\3\26\40\0\5\12\1\0\207\12\23\0\12\26"+
    "\7\0\32\12\4\0\1\26\1\0\32\12\13\0\131\12"+
    "\3\0\6\12\2\0\6\12\2\0\6\12\2\0\3\12"+
    "\43\0\14\12\1\0\32\12\1\0\23\12\1\0\2\12"+
    "\1\0\17\12\2\0\16\12\42\0\173\12\105\0\65\26"+
    "\210\0\1\26\202\0\35\12\3\0\61\12\17\0\1\26"+
    "\37\0\40\12\15\0\24\12\1\26\10\12\1\26\5\0"+
    "\46\12\5\26\5\0\36\12\2\0\44\12\4\0\10\12"+
    "\1\0\5\26\52\0\236\12\2\0\12\26\6\0\44\12"+
    "\4\0\44\12\4\0\50\12\10\0\64\12\234\0\67\12"+
    "\11\0\26\12\12\0\10\12\230\0\6\12\2\0\1\12"+
    "\1\0\54\12\1\0\2\12\3\0\1\12\2\0\27\12"+
    "\12\0\27\12\11\0\37\12\101\0\23\12\1\0\2\12"+
    "\12\0\26\12\12\0\32\12\106\0\70\12\6\0\2\12"+
    "\100\0\1\12\3\26\1\0\2\26\5\0\4\26\4\12"+
    "\1\0\3\12\1\0\35\12\2\0\3\26\4\0\1\26"+
    "\40\0\35\12\3\0\35\12\43\0\10\12\1\0\34\12"+
    "\2\26\31\0\66\12\12\0\26\12\12\0\23\12\15\0"+
    "\22\12\156\0\111\12\67\0\63\12\15\0\63\12\15\0"+
    "\44\12\4\26\10\0\12\26\306\0\35\12\12\0\1\12"+
    "\10\0\26\12\13\26\217\0\27\12\11\0\3\26\65\12"+
    "\17\26\37\0\12\26\17\0\4\26\55\12\13\26\25\0"+
    "\31\12\7\0\12\26\6\0\3\26\44\12\16\26\1\0"+
    "\12\26\4\0\1\12\2\26\11\0\43\12\1\26\2\0"+
    "\1\12\11\0\3\26\60\12\16\26\4\12\4\0\4\26"+
    "\3\0\12\26\1\12\1\0\1\12\43\0\22\12\1\0"+
    "\31\12\14\26\6\0\1\26\101\0\7\12\1\0\1\12"+
    "\1\0\4\12\1\0\17\12\1\0\12\12\7\0\57\12"+
    "\14\26\5\0\12\26\6\0\4\26\1\0\10\12\2\0"+
    "\2\12\2\0\26\12\1\0\7\12\1\0\2\12\1\0"+
    "\5\12\1\0\2\26\1\12\7\26\2\0\2\26\2\0"+
    "\3\26\2\0\1\12\6\0\1\26\5\0\5\12\2\26"+
    "\2\0\7\26\3\0\5\26\213\0\65\12\22\26\4\12"+
    "\5\0\12\26\4\0\1\26\1\12\40\0\60\12\24\26"+
    "\2\12\1\0\1\12\10\0\12\26\246\0\57\12\7\26"+
    "\2\0\11\26\27\0\4\12\2\26\42\0\60\12\21\26"+
    "\3\0\1\12\13\0\12\26\46\0\53\12\15\26\1\12"+
    "\7\0\12\26\66\0\33\12\2\0\17\26\4\0\12\26"+
    "\306\0\54\12\17\26\145\0\100\12\12\26\25\0\1\12"+
    "\240\0\10\12\2\0\47\12\7\26\2\0\7\26\1\12"+
    "\1\0\1\12\1\26\33\0\1\12\12\26\50\12\7\26"+
    "\1\12\4\26\10\0\1\26\10\0\1\12\13\26\56\12"+
    "\20\26\3\0\1\12\42\0\71\12\7\0\11\12\1\0"+
    "\45\12\10\26\1\0\10\26\1\12\17\0\12\26\30\0"+
    "\36\12\2\0\26\26\1\0\16\26\111\0\7\12\1\0"+
    "\2\12\1\0\46\12\6\26\3\0\1\26\1\0\2\26"+
    "\1\0\7\26\1\12\1\26\10\0\12\26\6\0\6\12"+
    "\1\0\2\12\1\0\40\12\5\26\1\0\2\26\1\0"+
    "\5\26\1\12\7\0\12\26\u0136\0\23\12\4\26\11\0"+
    "\232\12\146\0\157\26\21\0\304\12\274\0\57\12\321\0"+
    "\107\12\271\0\71\12\7\0\37\12\1\0\12\26\146\0"+
    "\36\12\2\0\5\26\13\0\60\12\7\26\11\0\4\12"+
    "\14\0\12\26\11\0\25\12\5\0\23\12\260\0\100\12"+
    "\200\0\113\12\4\0\1\26\1\12\67\26\7\0\4\26"+
    "\15\12\100\0\2\12\1\0\1\12\34\0\370\12\10\0"+
    "\363\12\15\0\37\12\61\0\3\12\21\0\4\12\10\0"+
    "\u018c\12\4\0\153\12\5\0\15\12\3\0\11\12\7\0"+
    "\12\12\3\0\2\26\306\0\5\26\3\0\6\26\10\0"+
    "\10\26\2\0\7\26\36\0\4\26\224\0\3\26\273\0"+
    "\125\12\1\0\107\12\1\0\2\12\2\0\1\12\2\0"+
    "\2\12\2\0\4\12\1\0\14\12\1\0\1\12\1\0"+
    "\7\12\1\0\101\12\1\0\4\12\2\0\10\12\1\0"+
    "\7\12\1\0\34\12\1\0\4\12\1\0\5\12\1\0"+
    "\1\12\3\0\7\12\1\0\u0154\12\2\0\31\12\1\0"+
    "\31\12\1\0\37\12\1\0\31\12\1\0\37\12\1\0"+
    "\31\12\1\0\37\12\1\0\31\12\1\0\37\12\1\0"+
    "\31\12\1\0\10\12\2\0\151\26\4\0\62\26\10\0"+
    "\1\26\16\0\1\26\26\0\5\26\1\0\17\26\120\0"+
    "\7\26\1\0\21\26\2\0\7\26\1\0\2\26\1\0"+
    "\5\26\325\0\55\12\3\0\7\26\7\12\2\0\12\26"+
    "\4\0\1\12\u0171\0\54\12\16\26\6\0\305\12\13\0"+
    "\7\26\51\0\104\12\7\26\1\12\4\0\12\26\246\0"+
    "\4\12\1\0\33\12\1\0\2\12\1\0\1\12\2\0"+
    "\1\12\1\0\12\12\1\0\4\12\1\0\1\12\1\0"+
    "\1\12\6\0\1\12\4\0\1\12\1\0\1\12\1\0"+
    "\1\12\1\0\3\12\1\0\2\12\1\0\1\12\2\0"+
    "\1\12\1\0\1\12\1\0\1\12\1\0\1\12\1\0"+
    "\1\12\1\0\2\12\1\0\1\12\2\0\4\12\1\0"+
    "\7\12\1\0\4\12\1\0\4\12\1\0\1\12\1\0"+
    "\12\12\1\0\21\12\5\0\3\12\1\0\5\12\1\0"+
    "\21\12\164\0\32\26\6\0\32\26\6\0\32\26\166\0"+
    "\327\12\51\0\65\12\13\0\336\12\2\0\u0182\12\16\0"+
    "\u0131\12\37\0\36\12\342\0\360\26\20\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29696];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\2\11\16\12\1\13\3\12";

  private static int [] zzUnpackAction() {
    int [] result = new int[29];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\27\0\27\0\27\0\27\0\27\0\27\0\27"+
    "\0\27\0\27\0\56\0\105\0\134\0\163\0\212\0\241"+
    "\0\270\0\317\0\346\0\375\0\u0114\0\u012b\0\u0142\0\u0159"+
    "\0\u0170\0\105\0\u0187\0\u019e\0\u01b5";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[29];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\2\14\1\15\1\14\1\16\1\14\1\17"+
    "\5\14\1\2\37\0\2\13\25\0\17\14\10\0\13\14"+
    "\1\20\3\14\10\0\11\14\1\21\5\14\10\0\12\14"+
    "\1\22\4\14\10\0\13\14\1\23\3\14\10\0\13\14"+
    "\1\24\3\14\10\0\15\14\1\25\1\14\10\0\11\14"+
    "\1\26\5\14\10\0\3\14\1\27\13\14\10\0\5\14"+
    "\1\30\11\14\10\0\5\14\1\31\11\14\10\0\15\14"+
    "\1\32\1\14\10\0\7\14\1\33\7\14\10\0\3\14"+
    "\1\34\13\14\10\0\5\14\1\35\11\14\10\0\12\14"+
    "\1\32\4\14\10\0\14\14\1\32\2\14";

  private static int [] zzUnpackTrans() {
    int [] result = new int[460];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\11\11\23\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[29];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /*************************************************************************
    * Código a copiar textualmente como parte de la definición de la clase
    *  del analizador léxico.
    *************************************************************************/
    
    public List<MiToken> tablaDeSimbolos = new ArrayList<>();
 
	/* Preguntar para que sin valor ... */
    private MiToken token(String nombre) {
        return new MiToken(nombre, this.yyline, this.yycolumn);
    }

    private MiToken token(String nombre, Object valor) {
        return new MiToken(nombre, this.yyline, this.yycolumn, valor);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MiLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Entrada no permitida: <" + yytext() + ">");
            }
            // fall through
          case 12: break;
          case 2:
            { /* Ignora los espacios en blanco */
            }
            // fall through
          case 13: break;
          case 3:
            { return token("PAR_ABRE", yytext());
            }
            // fall through
          case 14: break;
          case 4:
            { return token("PAR_CIERRA", yytext());
            }
            // fall through
          case 15: break;
          case 5:
            { return token("MULT", yytext());
            }
            // fall through
          case 16: break;
          case 6:
            { return token("MAS", yytext());
            }
            // fall through
          case 17: break;
          case 7:
            { return token("MENOS", yytext());
            }
            // fall through
          case 18: break;
          case 8:
            { return token("DIV", yytext());
            }
            // fall through
          case 19: break;
          case 9:
            { return token("ENTERO", yytext());
            }
            // fall through
          case 20: break;
          case 10:
            { return token("IDENTIFICADOR", yytext());
            }
            // fall through
          case 21: break;
          case 11:
            { return token("TIPO_DE_DATO", yytext());
            }
            // fall through
          case 22: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
