// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/ar/edu/unnoba/compilador/lexico.flex

package ar.edu.unnoba.compilador;

import java.util.List;
import java.util.ArrayList;
import java_cup.runtime.*;
import java_cup.sym;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class MiLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\7\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u1f00\1\u2400\1\u2500\2\u1f00\31\u0100\1\u2600\121\u0100\1\u2700"+
    "\4\u0100\1\u2800\1\u0100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00"+
    "\1\u2e00\53\u0100\1\u2f00\41\u1f00\1\u0100\1\u3000\1\u3100\1\u0100"+
    "\1\u3200\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u3a00\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u4100\1\u1f00\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00"+
    "\1\u4f00\1\u5000\1\u1f00\3\u0100\1\u5100\1\u5200\1\u5300\12\u1f00"+
    "\4\u0100\1\u5400\17\u1f00\2\u0100\1\u5500\41\u1f00\2\u0100\1\u5600"+
    "\1\u5700\2\u1f00\1\u5800\1\u5900\27\u0100\1\u5a00\2\u0100\1\u5b00"+
    "\45\u1f00\1\u0100\1\u5c00\1\u5d00\11\u1f00\1\u5e00\24\u1f00\1\u5f00"+
    "\1\u6000\1\u1f00\1\u6100\1\u6200\1\u6300\1\u6400\2\u1f00\1\u6500"+
    "\5\u1f00\1\u6600\1\u6700\1\u6800\5\u1f00\1\u6900\1\u6a00\4\u1f00"+
    "\1\u6b00\2\u1f00\1\u6c00\16\u1f00\246\u0100\1\u6d00\20\u0100\1\u6e00"+
    "\1\u6f00\25\u0100\1\u7000\34\u0100\1\u7100\14\u1f00\2\u0100\1\u7200"+
    "\u0b06\u1f00\1\u7300\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\5\1\22\0\1\1\1\2\6\0\1\3\1\4"+
    "\2\5\1\0\1\5\1\0\1\5\1\6\11\7\2\0"+
    "\1\10\1\11\1\10\1\12\1\0\32\13\4\0\1\13"+
    "\1\0\1\14\1\15\1\13\1\16\1\17\1\20\1\21"+
    "\1\13\1\22\2\13\1\23\1\13\1\24\1\25\2\13"+
    "\1\26\1\13\1\27\6\13\12\0\1\1\32\0\1\1"+
    "\11\0\1\13\12\0\1\13\4\0\1\13\5\0\27\13"+
    "\1\0\37\13\1\0\u01ca\13\4\0\14\13\16\0\5\13"+
    "\7\0\1\13\1\0\1\13\21\0\160\30\5\13\1\0"+
    "\2\13\2\0\4\13\1\0\1\13\6\0\1\13\1\0"+
    "\3\13\1\0\1\13\1\0\24\13\1\0\123\13\1\0"+
    "\213\13\1\0\7\30\246\13\1\0\46\13\2\0\1\13"+
    "\6\0\51\13\10\0\55\30\1\0\1\30\1\0\2\30"+
    "\1\0\2\30\1\0\1\30\10\0\33\13\4\0\4\13"+
    "\35\0\13\30\5\0\53\13\37\30\4\0\2\13\1\30"+
    "\143\13\1\0\1\13\7\30\2\0\6\30\2\13\2\30"+
    "\1\0\4\30\2\13\12\30\3\13\2\0\1\13\20\0"+
    "\1\13\1\30\36\13\33\30\2\0\131\13\13\30\1\13"+
    "\16\0\12\30\41\13\11\30\2\13\4\0\1\13\2\0"+
    "\1\30\2\0\26\13\4\30\1\13\11\30\1\13\3\30"+
    "\1\13\5\30\22\0\31\13\3\30\4\0\13\13\65\0"+
    "\25\13\1\0\10\13\25\0\17\30\1\0\41\30\66\13"+
    "\3\30\1\13\22\30\1\13\7\30\12\13\2\30\2\0"+
    "\12\30\1\0\20\13\3\30\1\0\10\13\2\0\2\13"+
    "\2\0\26\13\1\0\7\13\1\0\1\13\3\0\4\13"+
    "\2\0\1\30\1\13\7\30\2\0\2\30\2\0\3\30"+
    "\1\13\10\0\1\30\4\0\2\13\1\0\3\13\2\30"+
    "\2\0\12\30\2\13\12\0\1\13\1\0\1\30\2\0"+
    "\3\30\1\0\6\13\4\0\2\13\2\0\26\13\1\0"+
    "\7\13\1\0\2\13\1\0\2\13\1\0\2\13\2\0"+
    "\1\30\1\0\5\30\4\0\2\30\2\0\3\30\3\0"+
    "\1\30\7\0\4\13\1\0\1\13\7\0\14\30\3\13"+
    "\1\30\13\0\3\30\1\0\11\13\1\0\3\13\1\0"+
    "\26\13\1\0\7\13\1\0\2\13\1\0\5\13\2\0"+
    "\1\30\1\13\10\30\1\0\3\30\1\0\3\30\2\0"+
    "\1\13\17\0\2\13\2\30\2\0\12\30\11\0\1\13"+
    "\6\30\1\0\3\30\1\0\10\13\2\0\2\13\2\0"+
    "\26\13\1\0\7\13\1\0\2\13\1\0\5\13\2\0"+
    "\1\30\1\13\7\30\2\0\2\30\2\0\3\30\10\0"+
    "\2\30\4\0\2\13\1\0\3\13\2\30\2\0\12\30"+
    "\1\0\1\13\20\0\1\30\1\13\1\0\6\13\3\0"+
    "\3\13\1\0\4\13\3\0\2\13\1\0\1\13\1\0"+
    "\2\13\3\0\2\13\3\0\3\13\3\0\14\13\4\0"+
    "\5\30\3\0\3\30\1\0\4\30\2\0\1\13\6\0"+
    "\1\30\16\0\12\30\20\0\5\30\10\13\1\0\3\13"+
    "\1\0\27\13\1\0\20\13\3\0\1\13\7\30\1\0"+
    "\3\30\1\0\4\30\7\0\2\30\1\0\3\13\5\0"+
    "\2\13\2\30\2\0\12\30\20\0\1\13\3\30\1\0"+
    "\10\13\1\0\3\13\1\0\27\13\1\0\12\13\1\0"+
    "\5\13\2\0\1\30\1\13\7\30\1\0\3\30\1\0"+
    "\4\30\7\0\2\30\7\0\1\13\1\0\2\13\2\30"+
    "\2\0\12\30\1\0\2\13\15\0\4\30\1\0\10\13"+
    "\1\0\3\13\1\0\51\13\2\30\1\13\7\30\1\0"+
    "\3\30\1\0\4\30\1\13\5\0\3\13\1\30\7\0"+
    "\3\13\2\30\2\0\12\30\12\0\6\13\2\0\2\30"+
    "\1\0\22\13\3\0\30\13\1\0\11\13\1\0\1\13"+
    "\2\0\7\13\3\0\1\30\4\0\6\30\1\0\1\30"+
    "\1\0\10\30\6\0\12\30\2\0\2\30\15\0\60\13"+
    "\1\30\2\13\7\30\5\0\7\13\10\30\1\0\12\30"+
    "\47\0\2\13\1\0\1\13\1\0\5\13\1\0\30\13"+
    "\1\0\1\13\1\0\12\13\1\30\2\13\11\30\1\13"+
    "\2\0\5\13\1\0\1\13\1\0\6\30\2\0\12\30"+
    "\2\0\4\13\40\0\1\13\27\0\2\30\6\0\12\30"+
    "\13\0\1\30\1\0\1\30\1\0\1\30\4\0\2\30"+
    "\10\13\1\0\44\13\4\0\24\30\1\0\2\30\5\13"+
    "\13\30\1\0\44\30\11\0\1\30\71\0\53\13\24\30"+
    "\1\13\12\30\6\0\6\13\4\30\4\13\3\30\1\13"+
    "\3\30\2\13\7\30\3\13\4\30\15\13\14\30\1\13"+
    "\17\30\2\0\46\13\1\0\1\13\5\0\1\13\2\0"+
    "\53\13\1\0\115\13\1\0\4\13\2\0\7\13\1\0"+
    "\1\13\1\0\4\13\2\0\51\13\1\0\4\13\2\0"+
    "\41\13\1\0\4\13\2\0\7\13\1\0\1\13\1\0"+
    "\4\13\2\0\17\13\1\0\71\13\1\0\4\13\2\0"+
    "\103\13\2\0\3\30\40\0\20\13\20\0\126\13\2\0"+
    "\6\13\3\0\u016c\13\2\0\21\13\1\1\32\13\5\0"+
    "\113\13\3\0\3\30\10\13\7\0\15\13\1\0\4\13"+
    "\3\30\13\0\22\13\3\30\13\0\22\13\2\30\14\0"+
    "\15\13\1\0\3\13\1\0\2\30\14\0\64\13\40\30"+
    "\3\0\1\13\4\0\1\13\1\30\2\0\12\30\41\0"+
    "\3\30\2\0\12\30\6\0\131\13\7\0\5\13\2\30"+
    "\42\13\1\30\1\13\5\0\106\13\12\0\37\13\1\0"+
    "\14\30\4\0\14\30\12\0\12\30\36\13\2\0\5\13"+
    "\13\0\54\13\4\0\32\13\6\0\12\30\46\0\27\13"+
    "\5\30\4\0\65\13\12\30\1\0\35\30\2\0\13\30"+
    "\6\0\12\30\15\0\1\13\10\0\17\30\101\0\5\30"+
    "\57\13\21\30\7\13\4\0\12\30\21\0\11\30\14\0"+
    "\3\30\36\13\15\30\2\13\12\30\54\13\16\30\14\0"+
    "\44\13\24\30\10\0\12\30\3\0\3\13\12\30\44\13"+
    "\2\0\11\13\7\0\53\13\2\0\3\13\20\0\3\30"+
    "\1\0\25\30\4\13\1\30\6\13\1\30\2\13\3\30"+
    "\1\13\5\0\300\13\72\30\1\0\5\30\26\13\2\0"+
    "\6\13\2\0\46\13\2\0\6\13\2\0\10\13\1\0"+
    "\1\13\1\0\1\13\1\0\1\13\1\0\37\13\2\0"+
    "\65\13\1\0\7\13\1\0\1\13\3\0\3\13\1\0"+
    "\7\13\3\0\4\13\2\0\6\13\4\0\15\13\5\0"+
    "\3\13\1\0\7\13\3\0\13\1\35\0\2\1\5\0"+
    "\1\1\17\0\2\30\23\0\1\30\12\0\1\1\21\0"+
    "\1\13\15\0\1\13\20\0\15\13\63\0\41\30\21\0"+
    "\1\13\4\0\1\13\2\0\12\13\1\0\1\13\3\0"+
    "\5\13\6\0\1\13\1\0\1\13\1\0\1\13\1\0"+
    "\4\13\1\0\13\13\2\0\4\13\5\0\5\13\4\0"+
    "\1\13\21\0\43\30\2\13\4\30\u022d\0\64\30\26\0"+
    "\57\13\1\0\57\13\1\0\205\13\6\0\4\13\3\30"+
    "\2\13\14\0\46\13\1\0\1\13\5\0\1\13\2\0"+
    "\70\13\7\0\1\13\17\0\1\30\27\13\11\0\7\13"+
    "\1\0\7\13\1\0\7\13\1\0\7\13\1\0\7\13"+
    "\1\0\7\13\1\0\7\13\1\0\7\13\1\0\40\30"+
    "\57\0\1\13\320\0\1\1\4\0\2\13\1\30\31\0"+
    "\17\30\1\0\5\13\2\0\3\30\2\13\4\0\126\13"+
    "\2\0\2\30\2\0\3\13\1\0\132\13\1\0\4\13"+
    "\5\0\53\13\1\0\136\13\21\0\33\13\65\0\306\13"+
    "\112\0\360\13\20\0\215\13\103\0\56\13\2\0\15\13"+
    "\3\0\20\13\12\30\2\13\24\0\57\13\4\30\1\0"+
    "\12\30\1\0\37\13\2\30\106\13\14\30\45\0\11\13"+
    "\2\0\147\13\2\0\65\13\2\0\5\13\60\0\13\13"+
    "\1\30\3\13\1\30\4\13\1\30\27\13\5\30\30\0"+
    "\64\13\14\0\2\30\62\13\22\30\12\0\12\30\6\0"+
    "\22\30\6\13\3\0\1\13\1\0\2\13\13\30\34\13"+
    "\10\30\2\0\27\13\15\30\14\0\35\13\3\0\4\30"+
    "\57\13\16\30\16\0\1\13\12\30\6\0\5\13\1\30"+
    "\12\13\12\30\5\13\1\0\51\13\16\30\11\0\3\13"+
    "\1\30\10\13\2\30\2\0\12\30\6\0\27\13\3\0"+
    "\1\13\3\30\62\13\1\30\1\13\3\30\2\13\2\30"+
    "\5\13\2\30\1\13\1\30\1\13\30\0\3\13\2\0"+
    "\13\13\5\30\2\0\3\13\2\30\12\0\6\13\2\0"+
    "\6\13\2\0\6\13\11\0\7\13\1\0\7\13\1\0"+
    "\53\13\1\0\14\13\10\0\163\13\10\30\1\0\2\30"+
    "\2\0\12\30\6\0\244\13\14\0\27\13\4\0\61\13"+
    "\4\0\156\13\2\0\152\13\46\0\7\13\14\0\5\13"+
    "\5\0\1\13\1\30\12\13\1\0\15\13\1\0\5\13"+
    "\1\0\1\13\1\0\2\13\1\0\2\13\1\0\154\13"+
    "\41\0\153\13\22\0\100\13\2\0\66\13\50\0\14\13"+
    "\4\0\20\30\20\0\20\30\3\0\2\30\30\0\3\30"+
    "\40\0\5\13\1\0\207\13\23\0\12\30\7\0\32\13"+
    "\4\0\1\30\1\0\32\13\13\0\131\13\3\0\6\13"+
    "\2\0\6\13\2\0\6\13\2\0\3\13\43\0\14\13"+
    "\1\0\32\13\1\0\23\13\1\0\2\13\1\0\17\13"+
    "\2\0\16\13\42\0\173\13\105\0\65\30\210\0\1\30"+
    "\202\0\35\13\3\0\61\13\17\0\1\30\37\0\40\13"+
    "\15\0\24\13\1\30\10\13\1\30\5\0\46\13\5\30"+
    "\5\0\36\13\2\0\44\13\4\0\10\13\1\0\5\30"+
    "\52\0\236\13\2\0\12\30\6\0\44\13\4\0\44\13"+
    "\4\0\50\13\10\0\64\13\234\0\67\13\11\0\26\13"+
    "\12\0\10\13\230\0\6\13\2\0\1\13\1\0\54\13"+
    "\1\0\2\13\3\0\1\13\2\0\27\13\12\0\27\13"+
    "\11\0\37\13\101\0\23\13\1\0\2\13\12\0\26\13"+
    "\12\0\32\13\106\0\70\13\6\0\2\13\100\0\1\13"+
    "\3\30\1\0\2\30\5\0\4\30\4\13\1\0\3\13"+
    "\1\0\35\13\2\0\3\30\4\0\1\30\40\0\35\13"+
    "\3\0\35\13\43\0\10\13\1\0\34\13\2\30\31\0"+
    "\66\13\12\0\26\13\12\0\23\13\15\0\22\13\156\0"+
    "\111\13\67\0\63\13\15\0\63\13\15\0\44\13\4\30"+
    "\10\0\12\30\306\0\35\13\12\0\1\13\10\0\26\13"+
    "\13\30\217\0\27\13\11\0\3\30\65\13\17\30\37\0"+
    "\12\30\17\0\4\30\55\13\13\30\25\0\31\13\7\0"+
    "\12\30\6\0\3\30\44\13\16\30\1\0\12\30\4\0"+
    "\1\13\2\30\11\0\43\13\1\30\2\0\1\13\11\0"+
    "\3\30\60\13\16\30\4\13\4\0\4\30\3\0\12\30"+
    "\1\13\1\0\1\13\43\0\22\13\1\0\31\13\14\30"+
    "\6\0\1\30\101\0\7\13\1\0\1\13\1\0\4\13"+
    "\1\0\17\13\1\0\12\13\7\0\57\13\14\30\5\0"+
    "\12\30\6\0\4\30\1\0\10\13\2\0\2\13\2\0"+
    "\26\13\1\0\7\13\1\0\2\13\1\0\5\13\1\0"+
    "\2\30\1\13\7\30\2\0\2\30\2\0\3\30\2\0"+
    "\1\13\6\0\1\30\5\0\5\13\2\30\2\0\7\30"+
    "\3\0\5\30\213\0\65\13\22\30\4\13\5\0\12\30"+
    "\4\0\1\30\1\13\40\0\60\13\24\30\2\13\1\0"+
    "\1\13\10\0\12\30\246\0\57\13\7\30\2\0\11\30"+
    "\27\0\4\13\2\30\42\0\60\13\21\30\3\0\1\13"+
    "\13\0\12\30\46\0\53\13\15\30\1\13\7\0\12\30"+
    "\66\0\33\13\2\0\17\30\4\0\12\30\306\0\54\13"+
    "\17\30\145\0\100\13\12\30\25\0\1\13\240\0\10\13"+
    "\2\0\47\13\7\30\2\0\7\30\1\13\1\0\1\13"+
    "\1\30\33\0\1\13\12\30\50\13\7\30\1\13\4\30"+
    "\10\0\1\30\10\0\1\13\13\30\56\13\20\30\3\0"+
    "\1\13\42\0\71\13\7\0\11\13\1\0\45\13\10\30"+
    "\1\0\10\30\1\13\17\0\12\30\30\0\36\13\2\0"+
    "\26\30\1\0\16\30\111\0\7\13\1\0\2\13\1\0"+
    "\46\13\6\30\3\0\1\30\1\0\2\30\1\0\7\30"+
    "\1\13\1\30\10\0\12\30\6\0\6\13\1\0\2\13"+
    "\1\0\40\13\5\30\1\0\2\30\1\0\5\30\1\13"+
    "\7\0\12\30\u0136\0\23\13\4\30\11\0\232\13\146\0"+
    "\157\30\21\0\304\13\274\0\57\13\321\0\107\13\271\0"+
    "\71\13\7\0\37\13\1\0\12\30\146\0\36\13\2\0"+
    "\5\30\13\0\60\13\7\30\11\0\4\13\14\0\12\30"+
    "\11\0\25\13\5\0\23\13\260\0\100\13\200\0\113\13"+
    "\4\0\1\30\1\13\67\30\7\0\4\30\15\13\100\0"+
    "\2\13\1\0\1\13\34\0\370\13\10\0\363\13\15\0"+
    "\37\13\61\0\3\13\21\0\4\13\10\0\u018c\13\4\0"+
    "\153\13\5\0\15\13\3\0\11\13\7\0\12\13\3\0"+
    "\2\30\306\0\5\30\3\0\6\30\10\0\10\30\2\0"+
    "\7\30\36\0\4\30\224\0\3\30\273\0\125\13\1\0"+
    "\107\13\1\0\2\13\2\0\1\13\2\0\2\13\2\0"+
    "\4\13\1\0\14\13\1\0\1\13\1\0\7\13\1\0"+
    "\101\13\1\0\4\13\2\0\10\13\1\0\7\13\1\0"+
    "\34\13\1\0\4\13\1\0\5\13\1\0\1\13\3\0"+
    "\7\13\1\0\u0154\13\2\0\31\13\1\0\31\13\1\0"+
    "\37\13\1\0\31\13\1\0\37\13\1\0\31\13\1\0"+
    "\37\13\1\0\31\13\1\0\37\13\1\0\31\13\1\0"+
    "\10\13\2\0\151\30\4\0\62\30\10\0\1\30\16\0"+
    "\1\30\26\0\5\30\1\0\17\30\120\0\7\30\1\0"+
    "\21\30\2\0\7\30\1\0\2\30\1\0\5\30\325\0"+
    "\55\13\3\0\7\30\7\13\2\0\12\30\4\0\1\13"+
    "\u0171\0\54\13\16\30\6\0\305\13\13\0\7\30\51\0"+
    "\104\13\7\30\1\13\4\0\12\30\246\0\4\13\1\0"+
    "\33\13\1\0\2\13\1\0\1\13\2\0\1\13\1\0"+
    "\12\13\1\0\4\13\1\0\1\13\1\0\1\13\6\0"+
    "\1\13\4\0\1\13\1\0\1\13\1\0\1\13\1\0"+
    "\3\13\1\0\2\13\1\0\1\13\2\0\1\13\1\0"+
    "\1\13\1\0\1\13\1\0\1\13\1\0\1\13\1\0"+
    "\2\13\1\0\1\13\2\0\4\13\1\0\7\13\1\0"+
    "\4\13\1\0\4\13\1\0\1\13\1\0\12\13\1\0"+
    "\21\13\5\0\3\13\1\0\5\13\1\0\21\13\164\0"+
    "\32\30\6\0\32\30\6\0\32\30\166\0\327\13\51\0"+
    "\65\13\13\0\336\13\2\0\u0182\13\16\0\u0131\13\37\0"+
    "\36\13\342\0\360\30\20\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29696];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\2\6"+
    "\1\7\7\10\1\7\6\10\1\11\7\10\1\12\3\10";

  private static int [] zzUnpackAction() {
    int [] result = new int[36];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\31\0\31\0\62\0\31\0\31\0\31\0\31"+
    "\0\113\0\62\0\144\0\175\0\226\0\257\0\310\0\341"+
    "\0\372\0\31\0\31\0\u0113\0\u012c\0\u0145\0\u015e\0\u0177"+
    "\0\144\0\u0190\0\u01a9\0\u01c2\0\u01db\0\u01f4\0\u020d\0\u0226"+
    "\0\144\0\u023f\0\u0258\0\u0271";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[36];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\4\1\2\1\13\1\14\1\15\2\13\1\16"+
    "\1\13\1\17\1\13\1\20\1\21\2\13\1\2\42\0"+
    "\1\22\25\0\2\11\27\0\2\13\2\0\1\23\16\13"+
    "\6\0\2\13\2\0\1\23\11\13\1\24\4\13\6\0"+
    "\2\13\2\0\1\23\12\13\1\25\3\13\6\0\2\13"+
    "\2\0\1\23\10\13\1\26\5\13\6\0\2\13\2\0"+
    "\1\23\11\13\1\27\4\13\6\0\2\13\2\0\1\23"+
    "\12\13\1\30\3\13\6\0\2\13\2\0\1\23\13\13"+
    "\1\31\2\13\6\0\2\13\2\0\1\23\3\13\1\31"+
    "\12\13\6\0\2\13\2\0\1\23\12\13\1\32\3\13"+
    "\6\0\2\13\2\0\1\23\12\13\1\33\3\13\6\0"+
    "\2\13\2\0\1\23\14\13\1\34\1\13\6\0\2\13"+
    "\2\0\1\23\14\13\1\31\1\13\6\0\2\13\2\0"+
    "\1\23\10\13\1\35\5\13\6\0\2\13\2\0\1\23"+
    "\1\13\1\36\14\13\6\0\2\13\2\0\1\23\4\13"+
    "\1\37\11\13\6\0\2\13\2\0\1\23\4\13\1\40"+
    "\11\13\6\0\2\13\2\0\1\23\14\13\1\41\1\13"+
    "\6\0\2\13\2\0\1\23\6\13\1\42\7\13\6\0"+
    "\2\13\2\0\1\23\1\13\1\43\14\13\6\0\2\13"+
    "\2\0\1\23\4\13\1\44\11\13\6\0\2\13\2\0"+
    "\1\23\11\13\1\41\4\13\6\0\2\13\2\0\1\23"+
    "\13\13\1\41\2\13";

  private static int [] zzUnpackTrans() {
    int [] result = new int[650];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\4\11\11\1\2\11\21\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[36];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /*************************************************************************
    * Código a copiar textualmente como parte de la definición de la clase
    *  del analizador léxico.
    *************************************************************************/
    
    public List<MiToken> tablaDeSimbolos = new ArrayList<>();
 
	/* Preguntar para que sin valor ... */
    private MiToken token(String nombre) {
        return new MiToken(nombre, this.yyline, this.yycolumn);
    }

    private MiToken token(String nombre, Object valor) {
        return new MiToken(nombre, this.yyline, this.yycolumn, valor);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MiLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Entrada no permitida: <" + yytext() + ">");
            }
            // fall through
          case 11: break;
          case 2:
            { /* Ignora los espacios en blanco */
            }
            // fall through
          case 12: break;
          case 3:
            { return token("PAR_ABRE", yytext());
            }
            // fall through
          case 13: break;
          case 4:
            { return token("PAR_CIERRA", yytext());
            }
            // fall through
          case 14: break;
          case 5:
            { return token("OPERADOR_ARITMÉTICO", yytext());
            }
            // fall through
          case 15: break;
          case 6:
            { return token("ENTERO", yytext());
            }
            // fall through
          case 16: break;
          case 7:
            { return token("OPERADOR_COMPARACIÓN", yytext());
            }
            // fall through
          case 17: break;
          case 8:
            { return token("IDENTIFICADOR", yytext());
            }
            // fall through
          case 18: break;
          case 9:
            { return token("OPERADOR_LÓGICO", yytext());
            }
            // fall through
          case 19: break;
          case 10:
            { return token("TIPO_DE_DATO", yytext());
            }
            // fall through
          case 20: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
