
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ar.edu.unnoba.compilador;

/** CUP generated class containing symbol constants. */
public class MiParserSym {
  /* terminals */
  public static final int MENOS = 3;
  public static final int MULT = 4;
  public static final int ENTERO = 10;
  public static final int MENOS_UNARIO = 8;
  public static final int PAR_CIERRA = 7;
  public static final int EOF = 0;
  public static final int MAS = 2;
  public static final int PAR_ABRE = 6;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "PAR_ABRE",
  "PAR_CIERRA",
  "MENOS_UNARIO",
  "IDENTIFICADOR",
  "ENTERO"
  };
}

